version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
      - ./config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: store_front,store_front_test
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres:
